### ISSUE TITLE
MarketPlace not responsive

### ISSUE THREAD

**Issue by skullfaice42** [Incredibleflamer/Anime-batch-downloader-gui#65]
I was trying to use the MarketPlace feature to set a provider but its not working.  Nor is the manga section

Also, in the MarketPlace, I recommend adding 9Anime (I'm not too sure if there's criteria that has to be met for you to add it to the list of options but I just thought I should say it anyway.)

**Comment by V-VBallz** [comment]
Me too as well. The extensions in the marketplace are uninteractive

**Comment by TheYogMehta** [comment]
@skullfaice42 @V-VBallz sorry 😭 fixed version mismatch 🙏

**Comment by Watereatingfish** [comment]
YES IT WORKS!!1!! THANK YOU SO MUCH

**Comment by Watereatingfish** [comment]
Will the hianime extension ever be functional in the later future?

**Comment by TheYogMehta** [comment]
ye ofc

**Comment by TheYogMehta** [comment]
if you got any site which i can add lmk

**Comment by Watereatingfish** [comment]
Thanks!

**Comment by gylphkr12** [comment]
I have just patched to the new Version. The patch Is bugged out I think? Have already downloaded from the marketplace but since there is only pahe, it is not working. Wait let me copy the log to another post

**Comment by skullfaice42** [comment]
yes please add 9anime, also it looks like the provider is not getting properly saved

**Comment by TheYogMehta** [comment]
ooh let me see 2mins

**Comment by TheYogMehta** [comment]
@skullfaice42 @V-VBallz @Watereatingfish should be working fine now lmk if it doest work!

@Watereatingfish btw can you slide reddit link?

**Comment by V-VBallz** [comment]
YES IT WORKS!!!

**Comment by gylphkr12** [comment]
@TheYogMehta yeah that's why I'm also confused, have already checked out different common possibilities like deactivating my antivirus and rechecking with a common browser but the issue still persist. Will try with my VM after this .

**Comment by gylphkr12** [comment]
@TheYogMehta Will try later on, still at work. I will lyk if I need help later

**Comment by Watereatingfish** [comment]
![Image](https://github.com/user-attachments/assets/d6b6dfc8-d4dd-4def-8787-92b2302dde82)


And i never even spammed

**Comment by gylphkr12** [comment]
@Watereatingfish lmaoo

**Comment by gylphkr12** [comment]
@Watereatingfish btw can't seem to find your username

**Comment by gylphkr12** [comment]
@Watereatingfish btw already added you into mod

**Comment by TheYogMehta** [comment]
let me add u both hehe

**Comment by TheYogMehta** [comment]
ForsakenRespect1908 banned 😭  what

**Comment by TheYogMehta** [comment]
incredible_flamers add me @gylphkr12 @Watereatingfish

**Comment by TheYogMehta** [comment]
@V-VBallz link? to 9anime working on kiss ass anime rn hope it works out somehow

**Comment by V-VBallz** [comment]
Is 9anime an extension now?

**Comment by Watereatingfish** [comment]
I think the group got banned

**Comment by V-VBallz** [comment]
Yh

**Comment by Watereatingfish** [comment]
incredible flamer are you a moderator?

**Comment by gylphkr12** [comment]
Don't know why it got banned lmao, Made new one have already invited you as mod @TheYogMehta . I will redo the desc later on. I think you need to formalize and make a name for your app to formalize it.

**Comment by gylphkr12** [comment]
Kay will change the reddit community name

**Comment by Watereatingfish** [comment]
link ?

**Comment by gylphkr12** [comment]
https://www.reddit.com/r/StrawVerse/s/VaVlGpD8S5

**Comment by Watereatingfish** [comment]
If hianime isnt in india does that mean it can't be added as an extension? 😭😭 ( i can't watch anime in sub anymore im sorry )

**Comment by TheYogMehta** [comment]
@Watereatingfish  noo imma add hianime there is issue with megaup if that is fixed imma enable it again

**Comment by TheYogMehta** [comment]
@gylphkr12 @Watereatingfish thank you ❤ 
https://github.com/TheYogMehta/StrawVerse/releases/tag/v5.0.0

**Comment by Watereatingfish** [comment]
> [@gylphkr12](https://github.com/gylphkr12) [@Watereatingfish](https://github.com/Watereatingfish) thank you ❤ https://github.com/TheYogMehta/StrawVerse/releases/tag/v5.0.0

I'm so honoured 😭😭😭

**Comment by Watereatingfish** [comment]
Make sure to let me know when hianime ( or 9anime idk ) is added!

**Comment by Watereatingfish** [comment]
> Sorry to ask, but has it been fixed?

ive been asking the same question 3 days ago

**Comment by TheYogMehta** [comment]
wait marketplace still not working?

**Comment by Watereatingfish** [comment]
oh don't worry it's working now

**Comment by Watereatingfish** [comment]
why did you remove animekai ?

**Comment by TheYogMehta** [comment]
man animekai changes its code every months 😭  + i cant decrypt it

**Comment by Watereatingfish** [comment]
wait lemme check i got a list in my notepad

**Comment by Watereatingfish** [comment]
https://9animetv.to/

**Comment by TheYogMehta** [comment]
i think i might need to use vpn or something

**Comment by Watereatingfish** [comment]
ok another one

**Comment by Watereatingfish** [comment]
the rest don't work anymore :(

**Comment by TheYogMehta** [comment]
hianime mega extractor not working 😢

**Comment by Watereatingfish** [comment]
oof

**Comment by Watereatingfish** [comment]
i found a site called animet.to

**Comment by gylphkr12** [comment]
Btw I have tried building it from scratch and trying in my VMS and my VM also using docker on my server. The result is the same. @TheYogMehta Somehow this time after I finished downloading pahe from the marketplace, it wouldn't show at the provider drop down menu![IMG_20250614_184624.jpg](https://github.com/user-attachments/assets/1e073c2e-1192-4fa3-a4de-466f4e162da2)

![IMG_20250614_184618.jpg](https://github.com/user-attachments/assets/f5a12b8e-6714-4bba-98d7-8340073e5f35)

![IMG_20250614_184659.jpg](https://github.com/user-attachments/assets/e91b8e0a-a46f-4fe9-98b2-0e86c71e3d1b)

**Comment by TheYogMehta** [comment]
imma check 2mins

**Comment by TheYogMehta** [comment]
press `windows key + r` should open run 
in run type : `%appdata%` 
this should open appdata folder find strawverse
strawverse should contain /scrapers/Anime 

check pahe.js is present or not

**Comment by gylphkr12** [comment]
There is data inside it

 ![IMG_20250614_215813.jpg](https://github.com/user-attachments/assets/e9669b3c-1134-43c7-a280-2c003c680ec8)

**Comment by TheYogMehta** [comment]
@gylphkr12 got discord?

**Comment by TheYogMehta** [comment]
@Watereatingfish @gylphkr12 btw reddit banned again 🤣 it said you broke rule 2

**Comment by gylphkr12** [comment]
@TheYogMehta sorry been busy the past few days, mb rule 2 on reddit caused by no post by 4 days lmao. I will fix it later. For my discord Authenthic Visual Co. uwu . Oh yeah but still busy at the moment there's an upgrade on my office network infrastructure so still kinda tweaking most of it as a network engineer lmao.

**Comment by Watereatingfish** [comment]
i recently downloaded all the chapters of the one piece manga and i realized that almost 30 different chapters didn't download :(

Could you fix it and maybe also allow anime folders and manga folders to be different? 
thanks
